spring.application.name=SB_Web_JPA_CRUD



spring.datasource.url=jdbc:mysql://localhost:3306/sb_web_jpa_crud
spring.datasource.password=
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.dialect=org.dialect.MySQLDialect


